### ISSUE TITLE
Message appears twice after close app.

### ISSUE THREAD

**Issue by JanderSilv** [habilelabs/habilelabs-react-native-exit-on-double-press#1] opened 2020-04-17 23:39 UTC
I have read the code to understand why the message appears twice, but for me, the code's logic is correct to appear only the first time when clicks on the BackButton. Or maybe it this just happens in my App.

**Comment by morwalz** [comment] 2020-04-19 19:31
HI @JanderSilv, I checked and verified, it can not appear twice. if you post me a code sample then i can look into it.

**Comment by JanderSilv** [comment] 2020-04-19 19:47
I've just added the useExit function call inside of the Component.
![image](https://user-images.githubusercontent.com/42092038/79698164-636eda00-825d-11ea-8c8e-2b814eb5014e.jpg)

**Comment by morwalz** [comment] 2020-04-20 06:00
@JanderSilv  i tried this and it show up only once. i think the issue is linked to something else in your code. One possibility could be , you are using this code on many screens and it is there in stack navigator. It is being called from both screen so it show up twice. please confirm if this is the case.

**Comment by morwalz** [comment] 2020-04-20 07:03
@JanderSilv  i updated the code you can use latest version, 

   ` const isFocused = useIsFocused();
    useExitAppOnDoublePress({
        condition: isFocused
    });`

you need to pass condition like this with stack router so it get invoked only when screen is active.

**Comment by JanderSilv** [comment] 2020-04-20 12:58
Thanks for the help!

**Comment by morwalz** [comment] 2020-04-20 17:46
closing the issue as it is fixed now.

**Closed as completed by morwalz** 2020-04-20 17:46 UTC
